/*

    OPERADORES RELACIONAIS

    > = MAIOR | 5 > 2 = TRUE | CINCO É MAIOR DO QUE DOIS
    < = MENOR | 5 < 2 = FALSE | CINCO NÃO É MENOR DO QUE DOIS
    >= = MAIOR OU IGUAL | 8 >= 8 = TRUE | OITO É MAIOR OU IGUAL A OITO
    <= = MENOR OU IGUAL | 9<= 7 = FALSE | NOVE NÃO É MENOR OU IGUAL A 7
    == = IGUALDADE | 5 == 5 = TRUE | CINCO É IGUAL A CINCO
    != = NÃO IGUAL/DIFERENTE | 4 != 4 = FALSO | QUATRO NÃO É DIFERENTE DE QUATRO
    === = IDÊNTICO \ IDENTIDADE RESTRITA | 5 == '5' = TRUE | 5 === '5' = FALSE | NO PRIMEIRO EXEMPLO ELES TÊM A MESMA GRANDEZA E TIPOS DIFERENTES. NO SEGUNDO EXEMPLO, OS TIPOS SÃO DIFERENTES

*/